import { ArrowLeft, Download, ExternalLink, FileAudio, Link2, Share2 } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { featuredAnalysis, getAnalysis, getToneColor, type Analysis } from "@/lib/mockData";
import { Button, ConfidenceGauge, SectionEyebrow, StatusBadge, useToast, Waveform } from "@/components/Shared";

function ResultStat({ label, value }: { label: string; value: string }) { return <div className="border-l border-white/10 pl-4"><p className="text-[10px] uppercase tracking-[.14em] text-[#69756f]">{label}</p><p className="mt-2 font-mono text-sm font-semibold text-[#e6ece8]">{value}</p></div>; }
function IndicatorRow({ name, score, tone, explanation }: Analysis["indicators"][number]) { return <div className="py-4 first:pt-0 last:pb-0"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="h-1.5 w-1.5" style={{ backgroundColor: getToneColor(tone) }} /><p className="text-xs font-semibold text-[#dce4df]">{name}</p></div><span className="font-mono text-xs font-semibold" style={{ color: getToneColor(tone) }}>{score}%</span></div><div className="mt-3 h-1 bg-white/8"><div className="h-full transition-[width] duration-500" style={{ width: `${score}%`, backgroundColor: getToneColor(tone) }} /></div><p className="mt-2 text-xs leading-5 text-[#77837c]">{explanation}</p></div>; }

export default function AnalysisResult() {
  const [, params] = useRoute("/analysis/:id");
  const [, navigate] = useLocation();
  const { notify } = useToast();
  const analysis = getAnalysis(params?.id);
  const hasIndicators = analysis.indicators.length > 0;
  const share = () => { navigator.clipboard?.writeText(window.location.href); notify("Result link copied", "Share this simulated analysis with your team.", "info"); };
  return <div className="mx-auto max-w-[1250px] animate-page"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><Link href="/history" className="inline-flex items-center gap-2 text-xs font-semibold text-[#89948e] transition hover:text-white"><ArrowLeft size={14} />Back to history</Link><div className="flex items-center gap-2"><Button variant="secondary" onClick={() => notify("Report export queued", "Your report is being prepared for download.", "success")}><Download size={14} />Download report</Button><Button variant="secondary" onClick={share}><Share2 size={14} /><span className="hidden sm:inline">Share</span></Button></div></div>
    <section className="panel relative overflow-hidden p-5 lg:p-8"><div className="absolute right-0 top-0 h-64 w-64 translate-x-1/3 -translate-y-1/3 rounded-full bg-[#ff6a5f]/10 blur-[90px]" /><div className="relative grid gap-8 lg:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-3"><SectionEyebrow>Analysis result</SectionEyebrow><span className="rounded-full border border-[#f2b84b]/20 bg-[#f2b84b]/10 px-2 py-0.5 font-mono text-[9px] font-semibold uppercase tracking-[.12em] text-[#f2c66c]">Simulated</span></div><div className="mt-5 flex items-start gap-3"><span className="mt-1 flex h-10 w-10 shrink-0 items-center justify-center bg-[#ff6a5f]/10 text-[#ff887e]"><ShieldIcon /></span><div><h1 className="font-display text-3xl font-bold tracking-[-.05em] text-white lg:text-[42px]">Likely AI generated<span className="text-[#ff6a5f]">.</span></h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#9ca7a2]">The voice contains multiple markers commonly associated with synthetic generation.</p></div></div><div className="mt-8 grid grid-cols-2 gap-5 sm:grid-cols-4"><ResultStat label="AI probability" value={`${analysis.aiProbability}%`} /><ResultStat label="Human probability" value={`${analysis.humanProbability}%`} /><ResultStat label="Audio duration" value={analysis.duration} /><ResultStat label="Processing time" value={analysis.processingTime} /></div></div><div className="flex items-center justify-start lg:justify-end"><ConfidenceGauge score={analysis.confidence} size={190} /></div></div><div className="relative mt-8 flex flex-col gap-3 border-t border-white/8 pt-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><FileAudio size={15} className="text-[#76817c]" /><span className="text-xs font-semibold text-[#dce4df]">{analysis.fileName}</span><span className="font-mono text-[10px] text-[#69756f]">{analysis.id}</span></div><StatusBadge result={analysis.result} /></div></section>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="panel p-5 lg:p-6"><div className="flex items-start justify-between"><div><SectionEyebrow>Voice authenticity indicators</SectionEyebrow><h2 className="mt-2 font-display text-xl font-semibold text-white">What the signal says</h2></div><ExternalLink size={15} className="text-[#69756f]" /></div>{hasIndicators ? <div className="mt-6 divide-y divide-white/8">{analysis.indicators.map((indicator) => <IndicatorRow key={indicator.name} {...indicator} />)}</div> : <div className="mt-6 border border-dashed border-white/10 p-5 text-sm text-[#84908a]">Detailed indicator breakdown is available for the featured simulated result.</div>}</section><section className="space-y-5"><div className="panel p-5 lg:p-6"><SectionEyebrow>Why this result?</SectionEyebrow><h2 className="mt-2 font-display text-xl font-semibold text-white">A pattern, not a verdict</h2><p className="mt-4 text-sm leading-6 text-[#9aa59f]">VoiceGuard found a combination of unusually consistent spectral bands, constrained pitch movement, and repeated temporal signatures. Together, these signals push the confidence score toward synthetic generation.</p><div className="mt-5 border-l-2 border-[#ff6a5f] bg-[#ff6a5f]/[.06] px-4 py-3 text-xs leading-5 text-[#d9aaa5]">This is a simulated result for product demonstration. It should not be used as the sole basis for moderation, legal, or investigative decisions.</div></div><div className="panel p-5 lg:p-6"><SectionEyebrow>File preview</SectionEyebrow><h2 className="mt-2 font-display text-lg font-semibold text-white">Signal timeline</h2><div className="mt-5"><Waveform flagged height={78} /></div><div className="mt-3 flex justify-between font-mono text-[10px] text-[#67736c]"><span>00:00</span><span>01:24</span><span>02:48</span></div></div></section></div>
    <section className="panel mt-5 p-5 lg:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><SectionEyebrow>Detected events</SectionEyebrow><h2 className="mt-2 font-display text-xl font-semibold text-white">Moments worth reviewing</h2></div><button onClick={() => notify("Timeline marker copied", "The event list is ready to share.", "info")} className="inline-flex items-center gap-2 text-xs font-semibold text-[#aab5ae] hover:text-[#b8e94f]"><Link2 size={14} />Copy event list</button></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{analysis.events.map((event) => <div key={`${event.time}-${event.label}`} className="border border-white/8 bg-white/[.02] p-4"><div className="flex items-center justify-between"><span className="font-mono text-xs font-semibold text-[#b8e94f]">{event.time}</span><span className="h-1.5 w-1.5 bg-[#ff6a5f]" /></div><p className="mt-4 text-xs font-semibold text-[#dce4df]">{event.label}</p><p className="mt-1 text-xs leading-5 text-[#77837c]">{event.detail}</p></div>)}</div></section><div className="mt-6 flex justify-center"><Button variant="secondary" onClick={() => navigate("/analyze")}>Analyze another file</Button></div>
  </div>;
}

function ShieldIcon() { return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M12 3 5 6v5c0 4.5 2.8 8.5 7 10 4.2-1.5 7-5.5 7-10V6l-7-3Z" /><path d="m8.8 12 2.2 2.2 4.5-4.5" /></svg>; }
